# -*- coding: utf-8 -*-
"""Text to speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IgV41e2veKuhcZt8tQtU3eZsMojLAKV
"""

pip install gTTS googletrans==4.0.0-rc1

from googletrans import Translator
from gtts import gTTS
import os

# Initialize translator
translator = Translator()

# Input sentence (English or any language)
text = input("Enter a sentence: ")

# Target language
language = input("Enter language code (hi/ml/te/ta): ")

# Translate text
translated = translator.translate(text, dest=language)

# Output translated text
print("\n📄 Translated Text:")
print(translated.text)

# Convert translated text to speech
tts = gTTS(text=translated.text, lang=language)
tts.save("speech.mp3")

# Play audio
os.system("start speech.mp3")   # Windows
# os.system("afplay speech.mp3") # macOS
# os.system("mpg321 speech.mp3") # Linux

print("\n🔊 Speech generated successfully!")